# Default values for oai-smf.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

namespace: "oai"

wscpimage:
  registry: local
  repository: pragyasharmaa/wavescp
  version: releaseV1.4 
  pullPolicy: IfNotPresent

rpscpimage:
  registry: local
  repository: pragyasharmaa/redirectproxyscp
  version: wave-1
  pullPolicy: IfNotPresent

initscpimage:
  registry: local
  repository: pragyasharmaa/initscp
  version: v2.0
  pullPolicy: IfNotPresent

nfimage:
  registry: local
  repository: pragyasharmaa/oai-smf
  version: v1.2
  pullPolicy: IfNotPresent

tcpdumpimage:
  registry: local
  repository: corfr/tcpdump
  version: latest
  pullPolicy: IfNotPresent

## good to use when pulling images from docker-hub mention 
#imagePullSecrets: 
#  - name: "personalkey"

serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: "oai-smf-sa10"

podSecurityContext:
  runAsUser: 0
  runAsGroup: 0

securityContext:
  privileged: false

service:
  type: ClusterIP
  n4Port: 8805
  http1Port: 80
  http2Port: 9090
  wavescpPort: 10095
  rpscpPort: 10096

start:
  smf: true
  initscp: true
  wavescp: true
  rpscp: true
  tcpdump: false #start tcpdump collection to analyse but beware it will take a lot of space in the container/persistent volume

# create multus only if there is a need to have seperate N4 and Nsmf interfaces
multus:
  create: true
  nsmfIPmain: "10.100.16.10"
  nsmfIPnetmask: "16"
  nsmfIPGw: "10.100.10.1"

config:
  instance: "0"
  pidDirectory: "/var/run"
  smfInterfaceNameForN4: "net1"  # net1 if multus creation is true else eth0
  smfInterfaceNameForSBI: "net1" 
  smfInterfacePortForSBI: "80"
  smfInterfaceHttp2PortForSBI: "9090"
  smfApiVersion: "v1"
  dnsIpv4Address: "10.100.10.1" # configure the dns for UE don't use Kubernetes DNS
  dnsSecIpv4Address: "10.100.10.1" # configure the dns for UE don't use Kubernetes DNS
  registerNrf: "yes" # if wants to use NRF registry and discovery
  discoverUpf: "yes" # discovery UPF 
  useFqdnDns: "no" # use only when the DNS can resolve FQDN of other network functions
  amfIpv4Address: "10.100.15.10"
  amfPort: "80" # configure if NRF is not used
  amfApiVersion: "v1" # configure if NRF is not used
  amfFqdn: "oai-amf-svc" # configure if NRF is not used
  udmIpv4Address: "10.100.13.10"
  udmPort: "80" # configure if UDM is used
  udmApiVersion: "v2" # configure if UDM is used
  udmFqdn: "localhost" # configure if UDM is used
  nrfIpv4Address: "10.100.11.10"
  nrfPort : "80" 
  nrfApiVersion: "v1"
  nrfFqdn: "oai-nrf-svc" # configure if NRF can be reached using Kubernetes service
  upfIpv4Address: "10.100.17.10"
  upfFqdn0: "oai-spgwu-svc" # configure if NRF is not used and useFqdnDns is true
  waverip: "10.100.17.10" # IP of remote wave scp i.e. IP address of remote VNF
  wavescpPort: "10095"
  wavelip: "127.0.0.1"
  rpscpPort: "10096"
  rpscpip: "127.0.0.1"
  wavedip: "10.100.32.10"

## currently only used by tcpdump container to store the tcpdump, this volume will be shared between all the network functions
persistence:
  sharedvolume: false  # should be true when if wants to store the tcpdump of all the network functions at same place
  volumeName: managed-nfs-storage
  size: 1Gi


resources:
  define: false
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
   cpu: 100m
   memory: 256Mi

terminationGracePeriodSeconds: 30

readinessProbe: false
livenessProbe: false

nodeSelector: {}

nodeName:
