apiVersion: v1
kind: PersistentVolume
metadata:
  name: oai-gnb
  labels:
    io.kompose.service: oai-gnb
spec:
  capacity:
    storage: 100Mi
  accessModes:
    - ReadWriteMany
  storageClassName: standard
  hostPath:
    path: "/home/k8svolumes/gnb"
