# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

namespace: "oai"

wscpimage:
  registry: local
  repository: pragyasharmaa/wavescp
  version: releaseV1.4
  pullPolicy: IfNotPresent

rpscpimage:
  registry: local
  repository: pragyasharmaa/redirectproxyscp
  version: wave-1
  pullPolicy: IfNotPresent

initscpimage:
  registry: local
  repository: pragyasharmaa/initscp
  version: v2.0
  pullPolicy: IfNotPresent

nfimage:
  registry: local
  repository: pragyasharmaa/oai-amf
  version: v2.0
  pullPolicy: IfNotPresent

tcpdumpimage:
  registry: local
  repository: corfr/tcpdump
  version: latest
  pullPolicy: IfNotPresent

## good to use when pulling images from docker-hub mention 
#imagePullSecrets: 
#  - name: "personalkey"

serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: "oai-amf-sa10"

podSecurityContext:
  runAsUser: 0
  runAsGroup: 0

securityContext:
  privileged: true
  capabilities:
    add:
    - NET_ADMIN
    - NET_RAW

service:
  type: ClusterIP
  sctpPort: 38412
  http1Port: 80
  http2Port: 9090
  wavescpPort: 10095
  rpscpPort: 10096

start:
  amf: true
  initscp: true
  wavescp: true
  rpscp: true
  tcpdump: false #start tcpdump collection to analyse but beware it will take a lot of space in the container/persistent volume

### In case your gNB or emulator is outside of the cluster then you need an extra interface to communicate with gNB
## This interface will be for N1/N2/NGAP

multus:
  create: true
  namfIPmain: "10.100.15.10"
  namfIPnetmask: "16"
  namfIPGw: "10.100.10.1"

config:
  instance: "0"
  pidDirectory: "/var/run"
  mcc: "208"
  mnc: "95"
  regionId: "128"
  amfsetId: "1"
  servedGuamiMcc0: "208"
  servedGuamiMnc0: "95"
  servedGuamiRegionId0: "128"
  servedGuamiAmfSetId0: "1"
  servedGuamiMcc1: "460"
  servedGuamiMnc1: "11"
  servedGuamiRegionId1: "10"
  servedGuamiAmfSetId1: "1"
  plmnSupportMcc: "208"
  plmnSupportMnc: "95"
  plmnSupportTac: "0x00a000"
  sst0: "222"
  sd0: "123"
  #sst0: "1"
  #sd0: "0x010203"
  sst1: "1"
  sd1: "1"
  amfInterfaceNameForNGAP: "net1" # If multus creation is true then net1 else eth0
  amfInterfaceNameForN11: "net1"  # Service based interface
  smfInstanceId0: "1"  # Only configure if not using NRF
  smfIpv4Addr0: "10.100.16.10"
  smfHttpVersion0: "v1" # Only configure if not using NRF
  smfFqdn0: "localhost" # Only configure if not using NRF
  smfInstanceId1: "2"  # Currently disabled in the amf.conf no need to configure
  smfIpv4Addr1: "10.100.16.40"
  smfHttpVersion1: "v1" # Currently disabled in the amf.conf no need to configure
  smfFqdn1: "localhost" # Currently disabled in the amf.conf no need to configure
  nrfIpv4Addr: "10.100.11.10"
  nrfPort: 80
  nrfApiVersion: "v1"
  nrfFqdn: "oai-nrf-svc"  # amf communicates using FQDN
  ausfFqdn: "oai-ausf-svc"
  externalAusf: "yes"
  ausfIpv4Addr: "10.100.14.10"
  ausfPort: 80
  ausfApiVersion: "v1"
  nfRegistration: "yes" 
  smfSelection: "no" 
  useFqdnDns: "no"  # Important to avoid mentioning any static ip-address
  mySqlServer: "10.42.3.65"
  mySqlUser: "root" # used only if not using AUSF
  mySqlPass: "linux" # used only if not using AUSF
  mySqlDb: "oai_db" # used only if not using AUSF
  operatorKey: "63bfa50ee6523365ff14c1f45f88737d"  # should be same as in susbcriber database 
  waverip: "10.100.16.10" # IP of remote wave scp i.e. IP address of remote VNF
  wavescpPort: "10095"
  wavelip: "127.0.0.1"
  rpscpPort: "10096"
  rpscpip: "127.0.0.1"
  wavedip: "10.100.32.10"

persistence:
  sharedvolume: false
  volumeName: managed-nfs-storage
  size: 1Gi

resources:
  define: false
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
   cpu: 100m
   memory: 256Mi

terminationGracePeriodSeconds: 30

readinessProbe: false
livenessProbe: false

nodeSelector: {}

nodeName:
