apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition 
metadata:
  name: waved-net1
spec:
  config: '{ 
      "cniVersion": "0.3.0",
      "type": "macvlan",
      "master": "ens3",
      "mode": "bridge",
      "ipam": {
        "type": "static",
        "addresses": [
            {
              "address": "10.100.32.10/16",
              "gateway": "10.100.10.1"
            }
        ]
      }
    }'

---

apiVersion: v1
kind: Pod
metadata:
  name: wave-daemon
  labels:
    app: wave-daemon
  annotations:
    k8s.v1.cni.cncf.io/networks: waved-net1
spec:
  containers:
    - name: waved
      image: pragyasharmaa/waved:v2.0
      imagePullPolicy: IfNotPresent
      ports:
        - containerPort: 80
      #command: ["/bin/bash", "-c", "tail -f /dev/null"]
      #args: ["/etc/wave/waved"]
