apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition 
metadata:
  name: waveps-net1
spec:
  config: '{ 
      "cniVersion": "0.3.0",
      "type": "macvlan",
      "master": "ens3",
      "mode": "bridge",
      "ipam": {
        "type": "static",
        "addresses": [
            {
              "address": "10.100.33.10/16",
              "gateway": "10.100.10.1"
            }
        ]
      }
    }'

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: wave-ps-pv
  labels:
    name: wave-store-pv # important to avoid the volume not found error
spec:
  capacity:
    storage: 40Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: wave-storage-class
  mountOptions:
    - hard
    - nfsvers=4.1
  nfs:
    server: "172.16.1.179"
    path: "/dockerdata-nfs/WAVE-store/"

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata: 
  name: wave-ps-pvc
spec: 
  accessModes: 
    - ReadWriteOnce
  resources: 
    requests: 
      storage: 40Gi
  storageClassName: wave-storage-class

---

apiVersion: v1
kind: Pod
metadata:
  name: wave-persistent-server
  labels:
    app: wave-persistent-server
  annotations:
    k8s.v1.cni.cncf.io/networks: waveps-net1
spec:
  volumes:
    - name: wave-ps-storage
      persistentVolumeClaim:
        claimName: wave-ps-pvc
  containers:
    - name: wave-ps-container
      image: pragyasharmaa/wavestorage:v1.1
      imagePullPolicy: IfNotPresent
      ports:
        - containerPort: 80
      #command: ["/bin/bash", "-c", "--"]
      #args: ["while true; do sleep 10; done;"]
      volumeMounts:
        - mountPath: "/etc/wave/pserver_data"
          name: wave-ps-storage
