# Default values for oai-nrf.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

namespace: "oai"

wscpimage:
  registry: local
  repository: pragyasharmaa/wavescp
  version: releaseV1.4 
  pullPolicy: IfNotPresent

rpscpimage:
  registry: local
  repository: pragyasharmaa/redirectproxyscp
  version: wave-1
  pullPolicy: IfNotPresent

initscpimage:
  registry: local
  repository: pragyasharmaa/initscp
  version: v2.0
  pullPolicy: IfNotPresent

nfimage:
  registry: local
  repository: pragyasharmaa/oai-nrf
  version: v2.0
  pullPolicy: IfNotPresent

tcpdumpimage:
  registry: local
  repository: corfr/tcpdump
  version: latest
  pullPolicy: IfNotPresent

## good to use when pulling images from docker-hub mention 
#imagePullSecrets: 
#  - name: "personalkey"

serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: "oai-nrf-sa10"

podSecurityContext:
  runAsUser: 0
  runAsGroup: 0

securityContext:
  privileged: true
  capabilities:
    add:
    - NET_ADMIN
    - NET_RAW

service:
  type: ClusterIP
  http1Port: 80
  http2Port: 9090
  wavescpPort: 10095
  rpscpPort: 10096

start:
  nrf: true
  initscp: true
  wavescp: true
  rpscp: true
  tcpdump: false #start tcpdump collection to analyse but beware it will take a lot of space in the container/persistent volume

# create multus interface in case the NRF wants to use a separate interface 
# than kubernetes general CNI or it needs to be accessed from outside cluster network using ip-address. 


multus:
  nrfIpNg: "10.100.11.10"
  nrfGw: "10.100.10.1"
  nrfNetmaskNg: "16"  

config:
  instance: "0"
  pidDirectory: "/var/run"
  nrfInterfaceNameForSBI: "net1" # net1 if multus.create is set true
  nrfInterfacePortForSBI: "80"
  nrfInterfaceHttp2PortForSBI: "9090"
  nrfApiVersion: "v1"
  smfIP: "10.100.16.10" 
  wavescpPort: "10095"
  wavelip: "127.0.0.1"
  rpscpPort: "10096"
  rpscpip: "127.0.0.1"
  wavedip: "10.100.32.10"

persistence:
  sharedvolume: false
  volumeName: managed-nfs-storage
  size: 1Gi

resources:
  define: false
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
   cpu: 100m
   memory: 256Mi

terminationGracePeriodSeconds: 30

readinessProbe: false
livenessProbe: false

nodeSelector: {}

nodeName:
